# -----------------------------------------------------------
# Configuración de la Conexión a la Base de Datos (PostgreSQL)
# -----------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_db
spring.datasource.username=app_user
spring.datasource.password=micontrasena
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------------------------------------
# Configuración de JPA/Hibernate (ORM)
# -----------------------------------------------------------
# 'update' creará automáticamente las tablas USUARIOS y REGISTROS_DIARIOS [cite: 12, 16]
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.security.enabled=false
# -----------------------------------------------------------
# Configuración del Servidor Web
# -----------------------------------------------------------
server.port=8081